/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#ffffff",
        "primary": "#0a0a0a",
        "outline-variant": "#c4c7c7",
        "on-secondary-fixed-variant": "#5d4201",
        "tertiary-container": "#ff6b35",
        "surface-tint": "#d4af37",
        "tertiary": "#ff8c42",
        "surface": "#1a1a1a",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#000000",
        "primary-fixed": "#d4af37",
        "surface-bright": "#2a2a2a",
        "outline": "#d4af37",
        "on-primary-fixed": "#000000",
        "on-primary-container": "#d4af37",
        "surface-variant": "#1f1f1f",
        "on-surface-variant": "#e0e0e0",
        "surface-container-lowest": "#0a0a0a",
        "on-primary": "#ffffff",
        "background": "#0a0a0a",
        "secondary": "#d4af37",
        "on-tertiary-fixed-variant": "#000000",
        "surface-container-highest": "#2a2a2a",
        "on-secondary-container": "#000000",
        "primary-fixed-dim": "#b8941f",
        "secondary-fixed-dim": "#b8941f",
        "tertiary-fixed": "#ff6b35",
        "surface-container-high": "#252525",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#151515",
        "on-secondary-fixed": "#000000",
        "on-primary-fixed-variant": "#d4af37",
        "on-surface": "#ffffff",
        "inverse-surface": "#ffffff",
        "on-tertiary-fixed": "#000000",
        "secondary-fixed": "#ffd700",
        "secondary-container": "#d4af37",
        "surface-dim": "#0a0a0a",
        "error-container": "#ffdad6",
        "inverse-primary": "#0a0a0a",
        "surface-container": "#1a1a1a",
        "inverse-on-surface": "#0a0a0a",
        "on-secondary": "#000000",
        "tertiary-fixed-dim": "#ff8c42",
        "error": "#ba1a1a",
        "primary-container": "#1a1a1a"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
