/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1c1c",
        "primary": "#181919",
        "outline-variant": "#c4c7c7",
        "on-secondary-fixed-variant": "#5d4201",
        "tertiary-container": "#bcaa7f",
        "surface-tint": "#5f5e5e",
        "tertiary": "#6b5d39",
        "surface": "#f9f9f9",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#4b3e1d",
        "primary-fixed": "#e4e2e1",
        "surface-bright": "#f9f9f9",
        "outline": "#747878",
        "on-primary-fixed": "#1b1c1c",
        "on-primary-container": "#959494",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#444748",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "background": "#f9f9f9",
        "secondary": "#775a19",
        "on-tertiary-fixed-variant": "#534523",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-container": "#785a1a",
        "primary-fixed-dim": "#c8c6c6",
        "secondary-fixed-dim": "#e9c176",
        "tertiary-fixed": "#f5e1b3",
        "surface-container-high": "#e8e8e8",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "on-secondary-fixed": "#261900",
        "on-primary-fixed-variant": "#474747",
        "on-surface": "#1a1c1c",
        "inverse-surface": "#2f3131",
        "on-tertiary-fixed": "#241a00",
        "secondary-fixed": "#ffdea5",
        "secondary-container": "#fed488",
        "surface-dim": "#dadada",
        "error-container": "#ffdad6",
        "inverse-primary": "#c8c6c6",
        "surface-container": "#eeeeee",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#d8c598",
        "error": "#ba1a1a",
        "primary-container": "#2d2d2d"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
